name: Release on push to master

on:
  push:
    branches:
      - test-release

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Sem přijde tvůj build - vygeneruje soubory, které chceš publikovat
      - name: Build
        run: make

      - name: Generate version tag
        id: version
        run: echo "tag=v$(date +'%Y.%m.%d')-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: Release ${{ steps.version.outputs.tag }}
          body: " "
          files: vystupy/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
